name: pull-request

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Docker Compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
      # https://github.com/gradle/gradle-build-action
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle Build
        run: ./gradlew build